name: Build and Test

permissions:
  contents: read
  packages: write

on:
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      impls:
        description: 'Space separated list of impls to test (or all)'
        required: true
        default: 'all'

jobs:
  get-matrix:
    runs-on: ubuntu-24.04
    outputs:
      do-linux: ${{ steps.get-matrix-step.outputs.do_linux }}
      matrix-linux: ${{ steps.get-matrix-step.outputs.linux }}
      do-macos: ${{ steps.get-matrix-step.outputs.do_macos }}
      matrix-macos: ${{ steps.get-matrix-step.outputs.macos }}
    steps:
      - uses: actions/checkout@v4
      - id: files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: kanaka/get-changed-files@v2
        with:
          default_base: master
      - id: get-matrix-step
        run: |
          export OVERRIDE_IMPLS="${{ github.event.inputs.impls }}" # "
          echo "OVERRIDE_IMPLS: ${OVERRIDE_IMPLS}"
          ./get-ci-matrix.py ${{ steps.files.outputs.all }} > "${GITHUB_OUTPUT}"

  linux:
    needs: get-matrix
    if: ${{ needs.get-matrix.outputs.do-linux == 'true' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-linux) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for voom like versions
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build/Push
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh docker-build-push ${IMPL}
      - name: Build
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh build ${IMPL}
      - name: Step Tests
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh test ${IMPL}
      - name: Regression Tests
        run: |
          export ${{ matrix.IMPL }}
          STEP=stepA REGRESS=1 HARD=1 OPTIONAL=0 ./ci.sh test ${IMPL}
      - name: Performance Tests
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh perf ${IMPL}
      - name: Archive logs and debug output
        uses: actions/upload-artifact@v4
        with:
          name: logs.${{ matrix.IMPL }}
          path: |
            *.log
            *.debug

  macos:
    needs: get-matrix
    if: ${{ needs.get-matrix.outputs.do-macos == 'true' }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-macos) }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh build ${IMPL}
      - name: Step Tests
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh test ${IMPL}
      - name: Regression Tests
        run: |
          export ${{ matrix.IMPL }}
          STEP=stepA REGRESS=1 HARD=1 OPTIONAL=0 ./ci.sh test ${IMPL}
      - name: Performance Tests
        run: |
          export ${{ matrix.IMPL }}
          ./ci.sh perf ${IMPL}
      - name: Archive logs and debug output
        uses: actions/upload-artifact@v4
        with:
          name: logs.${{ matrix.IMPL }}
          path: |
            *.log
            *.debug
